### ISSUE TITLE
Add comments about LESS code

### ISSUE THREAD

**Issue by jel3569** [addb-swstarlab/LESS#1]
Since there are no comments on the code, it is difficult to analyze the code.

Could you add a comment on the LESS function? :-)

**Comment by addb-swstarlab** [comment]
Hi @jel3569  

We add description of LESS logging process and data recovery process.

Also, a code error was found and corrected while commenting.

*Data recovery process for errors that occurred during the first operation of LESS

If you have any questions about the added code, please let us know.

Since the reflection has been completed for the issue, we will close it.
